#!/bin/bash
chmod +x /var/lib/frost/web_app/publish/OpenSpeechTools;

cd /var/lib/frost;
echo "Moving to /var/lib/frost and cloning repos";
git clone https://github.com/fpga-open-speech-tools/deployment_manager.git;
cd /var/lib/frost/deployment_manager;
npm config set strict-ssl false;
npm install;

systemctl daemon-reload
echo "Starting and Enabling Frost Edge LKMs"
systemctl start frost_edge_lkms.service
systemctl enable frost_edge_lkms.service

echo "Starting and Enabling Frost Edge Web App"
systemctl start frost_edge_web_app.service
systemctl enable frost_edge_web_app.service

echo "Starting and Enabling Frost Edge Deployment Manager (DM)"
systemctl start frost_edge_dm.service
systemctl enable frost_edge_dm.service

systemctl daemon-reload