pipeline
{
    agent none
    stages
    {
        stage ('Ubuntu_20.04.1')
        {
            agent {label 'Ubuntu_20.04.1'}
            stages 
            {
                stage('Build Root File System')
                {
                    steps
                    {   dir("rootfs")
                        {
                            sh 'dos2unix docker_build.sh;'
                            sh 'dos2unix build_rootfs.sh;'
                            sh './docker_build.sh;'
                        }
                    }
                }
                stage('Archive')
                {
                    steps
                    {
                        dir("rootfs/")
                        {
                            archiveArtifacts artifacts: 'rootfs.tar.gz', fingerprint: true
                        }
                    }
                }
                stage('Cleanup')
                {
                    steps
                    {
                        deleteDir()
                        dir("${workspace}@tmp") {
                            deleteDir()
                        }
                    }
                } 
            }
        }
    }
}